# Generated by Django 4.0 on 2021-12-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('times', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
